### ISSUE TITLE
configure --enable-system-site-packages via spkg-configure.m4 for cvxopt and other python packages

### ISSUE THREAD

**Issue by thierry-FreeBSD** [sagemath/sage#29665]
<div id="comment:0"></div>

This ticket adds an spkg-configure.m4 for cvxopt and various other python packages, to allow them to be used from the system (part of #27330).

These python packages are special because we currently use a python "venv" that is isolated from the system. Thus this ticket proceeds in several steps:

1. Add an `--enable-system-site-packages` flag to the top-level `./configure` script. When present, this will tell `sage-venv` that the venv it creates **should not** be isolated from the system.
2. Create a new macro that can detect python packages on the system. It should ensure that the version bounds in each python package's `install-requires.txt` are met.
3. Create the `spkg-configure.m4` files themselves, which should be relatively simple at that point.
4. Test everything thoroughly with various combinations of system and non-system python packages.

Platform-specific testing:
- for example `TARGETS_PRE="build-local" EXTRA_CONFIGURE_ARGS="--enable-system-site-packages" tox -e docker-ubuntu-focal-standard -- build ptest`

Depends on #32703
Depends on #33067

Component: **build: configure**

Keywords: **cvxopt, system packages, Python library**

Author: **Michael Orlitzky**

Branch/Commit: **[u/mjo/ticket/29665](https://github.com/sagemath/sagetrac-mirror/tree/u/mjo/ticket/29665) @ [`baf6301`](https://github.com/sagemath/sagetrac-mirror/commit/baf63017c93ffb135f33e49c5a15bda33a5ecffb)**

_Issue created by migration from https://trac.sagemath.org/ticket/29665_

**Comment by orlitzky** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,13 +1,9 @@
-This ticket adds an spkg-configure.m4 for cvxopt, in order to use it from a system package if possible (see #27330).
+This ticket adds an spkg-configure.m4 for cvxopt and various other python packages, to allow them to be used from the system (part of #27330).
 
-This one is a bit special, because cvxopt is a Python module.
+These python packages are special because we currently use a python "venv" that is isolated from the system. Thus this ticket proceeds in several steps:
 
-The proposed attachment uses `python3`: I don´t like that, but at this point `$ac_path_PYTHON3` is not yet defined. (Note: on FreeBSD we have no python3 by default, and I have to patch it with the real versioned program name, but I guess that `python3` is more portable)
+1. Add an `--enable-system-site-packages` flag to the top-level `./configure` script. When present, this will tell `sage-venv` that the venv it creates **should not** be isolated from the system.
+2. Create a new macro that can detect python packages on the system. It should ensure that the version bounds in each python package's `install-requires.txt` are met.
+3. Create the `spkg-configure.m4` files themselves, which should be relatively simple at that point.
+4. Test everything thoroughly with various combinations of system and non-system python packages.
 
-To build Sage with it, `build/make/install` must be modified: it sets `PYTHONPATH` to `$SAGE_LOCAL`, and the system-wide Python modules are not found. It must be replaced by something like
-
-```
-"$SAGE_LOCAL:$SAGE_LOCAL/$PYTHON_SITELIBDIR:$PYTHON_SITELIBDIR"
-```
-
-with `$PYTHON_SITELIBDIR` being the site-packages directory used. So the Sage-built packages are always found in the first place, and those from the system are found when needed.
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -7,3 +7,6 @@
 3. Create the `spkg-configure.m4` files themselves, which should be relatively simple at that point.
 4. Test everything thoroughly with various combinations of system and non-system python packages.
 
+Platform-specific testing:
+- for example `EXTRA_CONFIGURE_ARGS="--enable-system-site-packages" tox -e docker-ubuntu-focal-standard -- build ptest`
+
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -8,5 +8,5 @@
 4. Test everything thoroughly with various combinations of system and non-system python packages.
 
 Platform-specific testing:
-- for example `EXTRA_CONFIGURE_ARGS="--enable-system-site-packages" tox -e docker-ubuntu-focal-standard -- build ptest`
+- for example `TARGETS_PRE="build-local" EXTRA_CONFIGURE_ARGS="--enable-system-site-packages" tox -e docker-ubuntu-focal-standard -- build ptest`
 
``````

**Comment by orlitzky** [comment]
> what's needing work here, besides rebasing?

Nothing, and I've rebased it at https://github.com/sagemath/sage/pull/36141

There's one test failure due to a deprecation warning in ipython somewhere, but I don't want to spend too much time chasing down minor test failures again. This is opt-in and I think it's a better use of time to get it merged and then deal with the issues rather than try to make it perfect before merging, given how many commits there are and how easily everything goes out of date.
