### ISSUE TITLE
Follow-up to #30335: Don't modify $SAGE_LOCAL contents from spkg-install scripts

### ISSUE THREAD

**Issue by embray** [sagemath/sage#30480]
<div id="comment:0"></div>

By design, spkg-install scripts should not directly touch the contents of `$SAGE_LOCAL`.  If some pre-/post-installation steps need to be taken to modify `$SAGE_LOCAL`, it should go in an `spkg-preinst` script.

I understand #30335 is a workaround, but the same workaround can still be implemented without violating this constraint.

In particular, there are numerous instances of removing bits of previous installations that can be found with

```
grep 'rm .*SAGE_LOCAL' build/pkgs/*/spkg-ins*
```
Most of these lines can probably be removed. For all packages that do DESTDIR staging, the lines would only be needed to clear out bits from ancient, pre-DESTDIR installations.

CC:  @mkoeppe @dimpase @jhpalmieri

Component: **build**

_Issue created by migration from https://trac.sagemath.org/ticket/30480_

**Comment by embray** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,3 @@
 By design, spkg-install scripts should not directly touch the contents of `$SAGE_LOCAL`.  If some pre-/post-installation steps need to be taken to modify `$SAGE_LOCAL`, it should go in an `spkg-preinst` script.
 
-I understand #30355 is a workaround, but the same workaround can still be implemented without violating this constraint.
+I understand #30335 is a workaround, but the same workaround can still be implemented without violating this constraint.
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,12 @@
 By design, spkg-install scripts should not directly touch the contents of `$SAGE_LOCAL`.  If some pre-/post-installation steps need to be taken to modify `$SAGE_LOCAL`, it should go in an `spkg-preinst` script.
 
 I understand #30335 is a workaround, but the same workaround can still be implemented without violating this constraint.
+
+In particular, there are numerous instances of removing bits of previous installations that can be found with
+
+```
+grep 'rm .*SAGE_LOCAL' build/pkgs/*/spkg-ins*
+```
+Most of these lines can probably be removed. For all packages that do DESTDIR staging, the lines would only be needed to clear out bits from ancient, pre-DESTDIR installations.
+
+
``````
