### ISSUE TITLE
Make jmol optional

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#31027]
<div id="comment:0"></div>

(split out from #30315)

We propose to downgrade jmol to optional.  

It used to be needed for
- ~~HTML docbuild~~ (not any more, as of Sage 10.5.beta2) -> #33507
- ~~sagetex testsuite~~ (not any more, as of Sage 10.5.beta2)
- ~~PDF docbuild~~ (not any more, as of Sage 10.5.beta2)

See discussion: ​https://groups.google.com/g/sage-devel/c/qKqTmLzHAbg/m/6YxQ_qWUBQAJ
 and #33507 for alternative technologies for creating 3D graphics for documentation and sagetex

Depends on #33507
Depends on #33534

CC:  @kcrisman @novoselt @jcamp0x2a @antonio-rojas @kiwifb @seblabbe @egourgoulhon @dimpase

Component: **build**

Author: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/31027_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -8,4 +8,4 @@
 so we make installation of jmol conditional on these.
 
 See discussion: ​https://groups.google.com/g/sage-devel/c/qKqTmLzHAbg/m/6YxQ_qWUBQAJ
-... also for alternative technologies for creating 3D graphics for documentation and sagetex
+ and #33507 for alternative technologies for creating 3D graphics for documentation and sagetex
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -3,8 +3,9 @@
 We propose to downgrade jmol to optional.  
 
 It is still needed for
+- HTML docbuild -> #33507
 - sagetex testsuite
-- PDF docbuild(?)
+- PDF docbuild
 so we make installation of jmol conditional on these.
 
 See discussion: ​https://groups.google.com/g/sage-devel/c/qKqTmLzHAbg/m/6YxQ_qWUBQAJ
``````

**Comment by orlitzky** [comment]
The docbuild is already pseudo-optional via `--disable-doc`. I think both sagetex and jmol are good candidates for being pseuso-optional as well: nothing else in sage needs sagetex at all, and nothing bad happens to a normal user who doesn't have jmol. Some other viewer is used by default, and if you try to _force_ jmol, you get an error. OK.

If we add `--disable-sagetex` and `--disable-jmol` flags, we could turn jmol off right now when both `--disable-doc` and `--disable-sagetex` are given. This would be merely a matter of accounting because, again, sage itself is fine without either sagetex or jmol.

(SageTeX should be completely optional because it's independent of _everything_, but we'll never get ML consensus to demote it.)

**Comment by mkoeppe** [comment]
Apparently (tested with #38504) the sagetex test suite no longer needs jmol to pass.

**Comment by mkoeppe** [comment]
Also docbuild (html and pdf) apparently no longer depends on jmol.
So let's go forward with demoting jmol to optional - #38504.
