### ISSUE TITLE
Add parameter 'induced' to `connected_subgraphs_iterator`

### ISSUE THREAD

**Issue by galen-dorp** [sagemath/sage#32136]
<div id="comment:0"></div>

This ticket adds:
- a method that, given a connected (di)graph `G = (V, E)`, returns an iterator over the connected subgraphs `H = (V, F)`, where `F` is a subset of `E`. 
- parameter `induced` to method connected_subgraphs_iterator`. When set to `True`, the method iterates over induced connected subgraphs (current behavior). When set to `False`, the method yields in addition the non-induced subgraphs.
- parameter `edges_only` to yield list of edges instead of graphs or list of vertices.

This ticket was opened based on [#32047#comment:6](https://github.com/sagemath/sage/issues/32047#comment:6) 

CC:  @dcoudert

Component: **graph theory**

Keywords: **connected graph, subgraph**

Author: **David Coudert**

Branch/Commit: **[public/graphs/32136_subgraph_iterator](https://github.com/sagemath/sagetrac-mirror/tree/public/graphs/32136_subgraph_iterator) @ [`e870546`](https://github.com/sagemath/sagetrac-mirror/commit/e87054681e1aa4a2d72f5027ffdb031abb5b0535)**

_Issue created by migration from https://trac.sagemath.org/ticket/32136_

**Comment by dcoudert** [comment]
Branch: **[public/graphs/32136_subgraph_iterator](https://github.com/sagemath/sagetrac-mirror/tree/public/graphs/32136_subgraph_iterator)**

**Comment by dcoudert** [comment]
Changed author from **Galen Dorpalen-Barry** to **David Coudert**

**Comment by dcoudert** [comment]
<div id="comment:5" align="right">comment:5</div>

This is a proposal for iterating over all non-induced subgraphs of a graph. I'm not sure that the name of the method is the best choice, but I don't have better proposals.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9eed85bc95c28581493cf3632cd26f85ff5ac397"><code>9eed85b</code></a></td><td><code>trac #32136: add iterator over full subgraphs</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f6136613085e0c9a8b74a9c3c4c8a4b44a87c3b7"><code>f613661</code></a></td><td><code>trac #32136: extend method connected_subgraph_iterator to non-induced subgraphs</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/78d9d93f8cd2d70bb0328980b9895d14cda52fb7"><code>78d9d93</code></a></td><td><code>trac #32136: fix doctests</code></td></tr></table>

**Comment by dcoudert** [comment]
Commit: **[`78d9d93`](https://github.com/sagemath/sagetrac-mirror/commit/78d9d93f8cd2d70bb0328980b9895d14cda52fb7)**

**Comment by dcoudert** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,3 @@
 Currently the `connected_subgraphs_iterator` returns sets of vertices whose induced subgraphs are connected. Instead, add a parameter `induced` to `connected_subgraphs_iterator`. When `induced` is set to False, the iterator should return the connected subgraphs themselves, rather than the vertices that induce connected subgraphs.
 
-This ticket was opened based on a suggestion from dcoudert on Ticket #32047.
+This ticket was opened based on a suggestion from David Coudert on Ticket #32047.
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`78d9d93`](https://github.com/sagemath/sagetrac-mirror/commit/78d9d93f8cd2d70bb0328980b9895d14cda52fb7)** to **[`9c3e732`](https://github.com/sagemath/sagetrac-mirror/commit/9c3e732c201e7ab5a767f732a42ad034042583c4)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9c3e732c201e7ab5a767f732a42ad034042583c4"><code>9c3e732</code></a></td><td><code>trac #32136: fix typos</code></td></tr></table>

**Comment by dcoudert** [comment]
<div id="comment:7" align="right">comment:7</div>

green bot, please review.

**Comment by dcoudert** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,6 @@
-Currently the `connected_subgraphs_iterator` returns sets of vertices whose induced subgraphs are connected. Instead, add a parameter `induced` to `connected_subgraphs_iterator`. When `induced` is set to False, the iterator should return the connected subgraphs themselves, rather than the vertices that induce connected subgraphs.
+This ticket adds:
+- a method that, given a connected (di)graph `G = (V, E)`, return an iterator over the connected subgraphs `H = (V, F)`, where `F` is a subset of `E`. 
+- parameter `induced` to method connected_subgraphs_iterator`. When set to `True`, the method iterates over induced connected subgraphs (current behavior). When set to `False`, the method yields in addition the non-induced subgraphs.
+- parameter `edges_only` to yield list of edges instead of graphs or list of vertices.
 
-This ticket was opened based on a suggestion from David Coudert on Ticket #32047.
+This ticket was opened based on [#32047#comment:6](https://github.com/sagemath/sage/issues/32047#comment:6) 
``````

**Comment by videlec** [comment]
<div id="comment:8" align="right">comment:8</div>

How complicated would it be to have parameters `min_num_edges`/`max_num_edges` in `connected_full_subgraphs`? I am asking because of https://gitlab.com/modulispaces/admcycles/-/issues/102.

**Comment by dcoudert** [comment]
<div id="comment:9" align="right">comment:9</div>

This is not difficult. I just need to figure out how to use some bitset intrisic to count the number of 1s in an unsigned long.

**Comment by videlec** [comment]
<div id="comment:10" align="right">comment:10</div>

Isn't it `static inline long _bitset_len(mp_limb_t* bits, mp_bitcnt_t limbs)` from `bitset_intrinsics.h`?

**Comment by dcoudert** [comment]
<div id="comment:11" align="right">comment:11</div>

Yes. For some (unkown) reason, I crashed my sage installation while trying to fix the problem. I'm currently recompiling from scratch. I'll try again soon.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9c3e732`](https://github.com/sagemath/sagetrac-mirror/commit/9c3e732c201e7ab5a767f732a42ad034042583c4)** to **[`e870546`](https://github.com/sagemath/sagetrac-mirror/commit/e87054681e1aa4a2d72f5027ffdb031abb5b0535)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e8ea54ba232ae29edd37699ba9e3c38f4b7b913a"><code>e8ea54b</code></a></td><td><code>trac #32136: merged with 9.8.beta2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/720368f24ab533c3d00903980528039ed0cb888c"><code>720368f</code></a></td><td><code>trac #32136: add bounds on the number of edges</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e87054681e1aa4a2d72f5027ffdb031abb5b0535"><code>e870546</code></a></td><td><code>trac #32136: fix result for digraphs</code></td></tr></table>

**Comment by dcoudert** [comment]
<div id="comment:13" align="right">comment:13</div>

This should answer #comment:8. I also fixed the output for digraphs.

**Comment by videlec** [comment]
<div id="comment:14" align="right">comment:14</div>

Thanks! Let me check this afternoon how it performs in admcycles. Also, I don't remember if I want a fixed number of edges or rather a fixed weight (as each edge carries a positive integral weight there).

**Comment by dcoudert** [comment]
<div id="comment:15" align="right">comment:15</div>

It is possible to also consider weights, but not efficiently. This can be considered in another ticket.

**Comment by videlec** [comment]
<div id="comment:16" align="right">comment:16</div>

Replying to [David Coudert](#comment%3A15):
> It is possible to also consider weights, but not efficiently. This can be considered in another ticket.

+1

**Comment by dcoudert** [comment]
<div id="comment:17" align="right">comment:17</div>

The random doctest errors reported by the patchbot in `src/sage/homology/tests.py` have been reported in #32544

**Comment by videlec** [comment]
<div id="comment:18" align="right">comment:18</div>

Replying to [Vincent Delecroix](#comment%3A16):
> Replying to [David Coudert](#comment%3A15):
> > It is possible to also consider weights, but not efficiently. This can be considered in another ticket.
> 
> 
> +1

In my application I have a simple graph `G` with positive integer weights on its edges and an integer `k`. I need to iterate through subset of edges 
- whose corresponding subgraph is connected
- of size at most `k` (the argument `min_edges` works for this)
- of total weight at least `k` (there is no such thing yet)

This ticket is still a good step forward. Thanks.

**Comment by dcoudert** [comment]
<div id="comment:19" align="right">comment:19</div>

If you are happy with this ticket, can we set it to positive review ? the patchbot is green

**Comment by dcoudert** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,5 +1,5 @@
 This ticket adds:
-- a method that, given a connected (di)graph `G = (V, E)`, return an iterator over the connected subgraphs `H = (V, F)`, where `F` is a subset of `E`. 
+- a method that, given a connected (di)graph `G = (V, E)`, returns an iterator over the connected subgraphs `H = (V, F)`, where `F` is a subset of `E`. 
 - parameter `induced` to method connected_subgraphs_iterator`. When set to `True`, the method iterates over induced connected subgraphs (current behavior). When set to `False`, the method yields in addition the non-induced subgraphs.
 - parameter `edges_only` to yield list of edges instead of graphs or list of vertices.
 
``````
