### ISSUE TITLE
Upstream Python distribution package for conway_polynomials

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#32747]
<div id="comment:0"></div>

... so that we can replace the Sage-specific installation script `build/pkgs/conway_polynomials/spkg-install.py` by just `pip install ...`

CC:  @orlitzky @antonio-rojas

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/32747_

**Comment by orlitzky** [comment]
These polynomials (by way of the same database) are all included with GAP. I'll create a PR that replaces our implementation with GAP's, and deprecates the sage module.

**Comment by mkoeppe** [comment]
I don't think that's a good idea from the modularization side of things. GAP is huge, this database is small and is needed for basic ring implementations already

**Comment by orlitzky** [comment]
Which piece of sage is going to wind up with the GAP dependency?

Punting to GAP does have another benefit. Our existing implementation throws a `RuntimeError` if you ask it for a polynomial that isn't in the database, but GAP will compute it for you.

**Comment by mkoeppe** [comment]
I'm not opposed to using GAP for providing additional functionality (providing Conway polynomials when it can, when our own code would have to fall back to pseudo-Conway).

**Comment by mkoeppe** [comment]
> Which piece of sage is going to wind up with the GAP dependency?

Looking for files `all__sagemath_gap.py` in #36676 (split out from #35095) gives a pretty good overview.

**Comment by mkoeppe** [comment]
I see the issue with the missing Conway database in testing distributions like sagemath-categories, sagemath-modules, etc. in #35095 -- large parts of Sage, basically everything that does not have to use non-abelian groups or the Universal Cyclotomic Field.

**Comment by orlitzky** [comment]
Ok, it was too good to be true I guess. I'll start reverse engineering the tarball on files.sagemath.org.

**Comment by orlitzky** [comment]
https://github.com/orlitzky/conway-polynomials/

Create a repo under the sage umbrella for it?

**Comment by mkoeppe** [comment]
Yes please!

Should the package be called "sagemath-database-conway-polynomials", as for example Debian calls it according to https://repology.org/project/sagemath-conway-polynomials/versions?

**Comment by orlitzky** [comment]
> Yes please!
> 
> Should the package be called "sagemath-database-conway-polynomials", as for example Debian calls it according to https://repology.org/project/sagemath-conway-polynomials/versions?

I was bikeshedding with myself over this. I don't think the "sagemath-" prefix is appropriate any more because the new package is completely independent of SageMath. It ships Frank Lübeck's upstream data file and produces a vanilla dict of coefficient lists. I **do** think the name _conway-polynomials-database_ would be more appropriate, in case someone wants to create a python package that actually does something with Conway polynomials. But then since this is a continuation of our existing _conway_polynomials_ package with the same version scheme, I decided to stop thinking about it and leave the name alone.

If you think it's better with "-database" at the end, do that and I'll update the package.

**Comment by orlitzky** [comment]
I forgot perhaps the strongest argument in favor of *conway-polynomials*: it's obvious that you should `import conway_polynomials` to use it.

**Comment by mkoeppe** [comment]
This all makes sense, thanks for the discussion. `conway_polynomials` is good.

**Comment by orlitzky** [comment]
If someone can create either https://github.com/sagemath/conway-polynomials or https://gitlab.com/sagemath/conway-polynomials and give me push access, I'll update the project URLs, date the NEWS entry, tag a release, and start working on the sage PR.

I'm happy to make the pypi release too, however that would work.

(I've preferred a hyphen over an underscore in the project name because otherwise, the underscore has to be normalized to a hyphen anyway to arrive at e.g. the correct pypi URL; https://peps.python.org/pep-0503/#normalized-names)

**Comment by mkoeppe** [comment]
https://github.com/sagemath/conway-polynomials is yours

**Comment by mkoeppe** [comment]
> I'm happy to make the pypi release too, however that would work.

I can add a GH Actions workflow that pushes to PyPI using the sagemath organization's credentials

**Comment by orlitzky** [comment]
> https://github.com/sagemath/conway-polynomials is yours

Thanks, I just pushed everything.

**Comment by mkoeppe** [comment]
> > I'm happy to make the pypi release too, however that would work.
> 
> I can add a GH Actions workflow that pushes to PyPI using the sagemath organization's credentials

Added.

OK to force-push the release tag so trigger the push to PyPI?

**Comment by orlitzky** [comment]
> OK to force-push the release tag to trigger the push to PyPI?

The first release is always missing some imporant file, but maybe this time will be different. AFAIK it's ready.

**Comment by mkoeppe** [comment]
Done. https://github.com/sagemath/conway-polynomials/actions/runs/6975816351/job/18983452508#step:7:37

https://pypi.org/project/conway-polynomials/0.6/

**Comment by orlitzky** [comment]
> The first release is always missing some imporant file, but maybe this time will be different. AFAIK it's ready.

And now that it's published I see that a tuple would be much more appropriate than a list for the coefficients.

**Comment by orlitzky** [comment]
I tagged a v0.7 if you could please re-push it.

**Comment by mkoeppe** [comment]
https://pypi.org/project/conway-polynomials/0.7/
