### ISSUE TITLE
ideals of non-maximal orders in number fields

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34198]
<div id="comment:0"></div>

Currently (Sage 9.6), trying to construct an ideal of a non-maximal order in a number field errors out.

We should at least have a basic implementation that supports the standard ideal operations. This can serve as a foundation to which specialized code (such as for class-group computations, cf. #27413) can later be added as needed.

Component: **number fields**

_Issue created by migration from https://trac.sagemath.org/ticket/34198_

**Comment by grhkm21** [comment]
Hi, this is my first time contributing to Sage (iirc). I would like to help on this, since it seems critical to get things related to endomorphism rings of elliptic curves into Sage.

I saw that https://github.com/sagemath/sage/issues/27413 essentially already has a working implementation (commit https://github.com/sagemath/sagetrac-mirror/commit/3df71d581a10a14a5399b79f666560e1fd2dfc6b, I haven't checked whether all methods are implemented, but it seems that the core functionalities of constructing an ideal in a non-maximal order are there). Will that be a good place to start on, or are there any reasons it doesn't work here?

**Comment by yyyyx4** [comment]
I've pushed the somewhat unfinished branch I had lying around for this. It probably needs a little bit more work, such as implementing an ideal `.factor()` method: The other branch you mentioned seems to have `.prime_factors()`, so maybe we can copy that over and then implement `.factor()` on top of it?

(I would leave class-group-related functionality for a future issue.)
