### ISSUE TITLE
modernize super in root_systems

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34743]
<div id="comment:0"></div>

using the short syntax `super()` where possible

Component: **combinatorics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`512fcf8`](https://github.com/sagemath/sagetrac-mirror/commit/512fcf88770e4e434617bcc356500ee6aa2492dc)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34743_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/712322b42271ce01ec3e2bf2ab74a332d5db7db9"><code>712322b</code></a></td><td><code>modernize super in root_systems</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/30baa084e97e47798795f13dccd279464aca308f"><code>30baa08</code></a></td><td><code>modern super in root_systems, step 2</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34743](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34743)**

**Comment by fchapoton** [comment]
Commit: **[`30baa08`](https://github.com/sagemath/sagetrac-mirror/commit/30baa084e97e47798795f13dccd279464aca308f)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
<div id="comment:3" align="right">comment:3</div>

Merge failure on top of:

f2fa7597737 Trac #34741: OS X 13: filter out dylib warning

a4748c342ab Trac #34738: tiny details in symbolic min and max

fb213dfda77 Trac #34769: use libgap in simplicial_complex

01beb6a1069 Trac #34765: meson: Add spkg-configure.m4

d94c7334140 Trac #34762: Fix random chain complex doctest

b3398f0543d Trac #34761: Remove src/sage/libs/fes.pyx

3c42a395c22 Trac #34754: Remove module-level imports from sage.plot

0d120581338 Trac #34569: Fix some quasimodular forms rings methods for congruence subgroups

84f02afa5c8 Updated [SageMath](../wiki/SageMath) version to 9.8.beta4

03f68f4aa96 Trac #34737: less use of gap.eval in linear code

96c4ae9184a Trac #34735: some details in hyperelliptic_padic_field

f9cee4ddd29 Trac #34731: math display broken because of missing .

1b9ac4d11cd Trac #34727: .multiplication_by_m_isogeny() fails for negative m

bcabe95d75f Trac #34723: elliptic_curves/hom_velusqrt.py: random test failure

8e1b55bb21e Trac #34710: Keep object entries in TOC in short form

576ea23021f Trac #34746: Upgrade cmake to 3.24.3, increase minimum system cmake version to 3.11

6cc6cf548ee Trac #34739: get rid of some usage of "long" python2 type in pyx files

80c3f4658dc Trac #34736: cleanup for QQ-curves

e338c18b412 Trac #34733: polynomial quo_rem gives wrong answer for noncommutative rings

6fda98d9de9 Trac #34732: more opportunistic caching of elliptic-curve and point orders

d883104bb2e Trac #34692: Frobenius endomorphism creation fail for infinite ring extension

df312d1b178 Trac #30217: tox.ini: Add tests with Ubuntu + deadsnakes

b52855ecc64 Trac #34730: Rebase sage_autodoc to sphinx 5.3.0

1df550e3c3d Trac #34729: topcom now requires autotools

c4edf81bf10 Trac #34709: fix cython warning in blas_dict

a30f206758b Trac #34652: Import NN directly rather than lazily throughout the Sage library

4b9a50080bd Trac #34589: VectorFieldModule, TensorFieldModule, DiffFormModule: Add methods tensor_product, tensor_power, update category of TensorFieldModule

9e0f15669b9 Trac #33878: Upgrade cypari2 to 2.1.3

cf0b066c0d9 Trac #32570: tox.ini, GH Actions: Update macOS environments to macOS 11, 12

9574dd15131 Trac #26084: Detect default colorscheme (dark/light)

94bdf2f12f3 Trac #18917: Speed up NumberField.zeta()

b641e6f0166 Trac #34724: echelonize() on RR matrices should not use "classical" algorithm

5048fd4c544 Trac #34081: Upgrade scipy to 1.9.x, add meson toolchain

8443dc3d8a5 Trac #34719: move carmichael_lambda() from sage.crypto.util to sage.arith.misc

4edaafebeed Trac #34716: fix assertion failure in _discrete_log_pgroup() when group is trivial

50977491440 Trac #34705: fix and activate W605 and E306 in pyx files

127c01cd4a9 Trac #34704: clean whitespace W293 in py files

4f157b7bddc Trac #34703: remove traces of lgtm

30d86af37d2 Trac #34676: Upgrade pip 22.3 and various other Python packages

17cc8b3d400 Trac #34654: Pickling frobenius endomorphism is broken

642f1157431 Trac #24462: Add tests that discriminant() of number fields is Integer

69f026a80d4 Trac #34713: Update IPython to 8.6

a2850f84bd2 Trac #34712: partial pep8 cleanup for number_field.py

3478e6fa5d3 Trac #34707: Bug in Clifford algebra multiplication

dee975299c2 Trac #34702: fix deprecated use of PyEval_Call*

3b6033475ee Trac #34681: Error with multiplication of points on elliptic curves over Integers(n)

4b482ce49c9 Trac #34651: Add `multivariate_interpolation` for multivariate polynomial rings

139fe8eaa0b Trac #34611: fast implementation of exp

c709fa42921 Trac #34397: pycodestyle cleanup in src/sage/graphs/generic_graph.py (part 9)

58c9281ec67 Trac #32267: make hadamard_matrix() use all the Hadamard matrices Sage knows

edfa1f93738 Trac #30423: F-Matrix Factory

7aa226ced2f Trac #34699: some details about INPUT and INPUT in the doc

c4079b7488c Trac #34697: minor fixes in doc in pyx files

813072800d9 Trac #34691: companion matrix of constant polynomial has the wrong parent

6b70584ab66 Trac #34638: refresh the file categories/rings.py

f634f6b0195 Trac #34368: implement the F,H,M triangles

859c3516190 Trac #34689: make Compositions() an additive monoid

b5082885f9a Trac #34665: openssl spkg-configure.m4: Also require openssl if curl needs to be built

487f2f9bca8 Trac #34662: sage.combinat.permutation.from_cycles produces wrong result when 'cycles' is a generator

ab0944d9eaf Trac #34636: make sparsity a decision of the user

24d0a8a1219 Trac #34381: Add infinite q-Pochhammer symbol

ef1d3d23588 Trac #34260: Implement northwest diagrams

bff11ac3b18 Trac #33176: Fix a few cython "referenced before assignment" warnings

89af3469590 Trac #32267: make hadamard_matrix() use all the Hadamard matrices Sage knows

c3028e74d80 Updated [SageMath](../wiki/SageMath) version to 9.8.beta3



merge was not clean: conflicts in src/sage/algebras/fusion_rings/fusion_ring.py,src/sage/combinat/root_system/weyl_characters.py

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/512fcf88770e4e434617bcc356500ee6aa2492dc"><code>512fcf8</code></a></td><td><code>Merge branch 'u/chapoton/34743' in 9.8.b4</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`30baa08`](https://github.com/sagemath/sagetrac-mirror/commit/30baa084e97e47798795f13dccd279464aca308f)** to **[`512fcf8`](https://github.com/sagemath/sagetrac-mirror/commit/512fcf88770e4e434617bcc356500ee6aa2492dc)**

**Comment by fchapoton** [comment]
<div id="comment:5" align="right">comment:5</div>

rebased, needs review again

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/512fcf88770e4e434617bcc356500ee6aa2492dc"><code>512fcf8</code></a></td><td><code>Merge branch 'u/chapoton/34743' in 9.8.b4</code></td></tr></table>

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34743](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34743)** to **[`512fcf8`](https://github.com/sagemath/sagetrac-mirror/commit/512fcf88770e4e434617bcc356500ee6aa2492dc)**
