### ISSUE TITLE
MixedIntegerLinearProgram.add_constraint: Allow False, True

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34882]
<div id="comment:0"></div>

follow up from #34878

Also `p.linear_constraints_parent()(False)`

CC:  @mantepse

Component: **linear programming**

_Issue created by migration from https://trac.sagemath.org/ticket/34882_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
 follow up from #34878
+
+Also `p.linear_constraints_parent()(False)`
``````

**Comment by mantepse** [comment]
<div id="comment:2" align="right">comment:2</div>

Meanwhile I understand that it woul be hard to do something sensible with `p.linear_constraints_parent()(False)`, because it should probably be the same as `p.linear_constraints_parent()(ZZ(0))`, and this is used as the building block for chained (in)equalities.  More precisely, it does not make sense (to me) to attach a truth value to `p.linear_constraints_parent()(False)`.

**Comment by mantepse** [comment]
<div id="comment:3" align="right">comment:3</div>

There is actually a doctest introduced in #13646 that checks that `True`/`False` input fail, but I think it is outdated.

**Comment by mantepse** [comment]
<div id="comment:4" align="right">comment:4</div>

Matthias, you wrote in [#34878 comment:22](https://github.com/sagemath/sage/issues/34878#comment:22):

> It would be OK with me for
>
>
>* p.add_constraint(True) to add the trivial constraint "0 <= 0"
>* p.add_constraint(False) to add the infeasible constraint "0 <= -1" 

Wouldn't it be better to ignore `p.add_constraint(True)` entirely?

I am surprised how tricky this little modification is.  In particular, it also affects `_is_redundant_constraint`.

**Comment by mantepse** [comment]
<div id="comment:5" align="right">comment:5</div>

To give some background, in #33238 I have, repeatedly, things like

```
                c = AZ_matrix[z][w] - B_matrix[z][w]
                if c.is_zero():
                    continue
                if c in ZZ:
                    raise MIPSolverException
                self.milp.add_constraint(c == 0, name="statistics")
```
Since the code is already hard to read, just having

```
                self.milp.add_constraint(AZ_matrix[z][w] == B_matrix[z][w], name="statistics")
```
seems nicer.  Moreover, the check `c in ZZ` seems brittle.  I guess I could use

```
               if c.coefficient(-1):
```
instead, but this also looks quite obscure.

Do you have an estimate for when #34251 will be ready?  How does CVXPY deal with trivially feasible / infeasible constraints?

**Comment by mantepse** [comment]
<div id="comment:6" align="right">comment:6</div>

Oops, it would have to be `if c.coefficient(-1) and (c - c.coefficient(-1)).is_zero():`.

**Comment by mantepse** [comment]
<div id="comment:7" align="right">comment:7</div>

I am now convinced that this is not a good idea.  It is much better to make the user convert the input to a linear constraint themselves.

**Comment by mantepse** [comment]
<div id="comment:8" align="right">comment:8</div>

In my case, if I simply make sure that `AZ_matrix[z][w] - B_matrix[z][w]` is a `LinearFunction`, everything works just fine.

**Comment by mkoeppe** [comment]
<div id="comment:9" align="right">comment:9</div>

Yes, working within the linear function parent is, of course, the correct solution.

**Comment by mkoeppe** [comment]
<div id="comment:10" align="right">comment:10</div>

Replying to [Martin Rubey](#comment%3A5):
> How does CVXPY deal with trivially feasible / infeasible constraints?

Usually modeling frameworks have a specialized function for forming fast sums, which also guarantees that the empty sum has the correct type. (Also Sage has `MixedIntegerLinearProgram.sum` for the same purpose.)
