### ISSUE TITLE
Adding class Kissat in sage/sat/solvers/dimacs.py

### ISSUE THREAD

**Issue by seblabbe** [sagemath/sage#34911]
<div id="comment:0"></div>

We add a class Kissat in sage/sat/solvers/dimacs.py

We also use the opportunity to improve the dimacs.py file (uniformize the classes so that they can inherit the same `__call__` method, added documentation and new doctests).

This is a follow up of #34909.

Depends on #34909

Component: **packages: optional**

Author: **Sébastien Labbé**

Branch/Commit: **[`27a3125`](https://github.com/sagemath/sagetrac-mirror/commit/27a312593d6c1a341b9b8f88dc2dce1a680d03fd)**

Reviewer: **Andrey Belgorodski**

_Issue created by migration from https://trac.sagemath.org/ticket/34911_

**Comment by seblabbe** [comment]
<div id="comment:1"></div>

Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8262dcd19b6d17d883e23a09a6f058b232ec9f44"><code>8262dcd</code></a></td><td><code>using just a spkg-install.in with no spkg-build.in</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ae362016bb9602f847bf600ae603f0aad3ef0f7a"><code>ae36201</code></a></td><td><code>build/pkgs/kissat/SPKG.rst: Fix title format, remove empty section</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cea9e49788f000e08d99646d063cd1c271d9396a"><code>cea9e49</code></a></td><td><code>build/pkgs/kissat: Fix scripts</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a9913725f7081e7b4c409f54708ecc5f14ea9183"><code>a991372</code></a></td><td><code>build/pkgs/kissat/distros: Add more</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1ad4eb03c9276cfe8fc38e009c78c28527f20ace"><code>1ad4eb0</code></a></td><td><code>renaming DIMACS.__call__ as DIMACS._run; moving RSat.__call__ up to parent DIMACS.__call__; improved doc</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0203eb370dcd4c2191383455c2c1098a3dc6f68d"><code>0203eb3</code></a></td><td><code>Adding class Kissat</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7f0b65e2497318f96250670703548408aa99bc96"><code>7f0b65e</code></a></td><td><code>Improved the output parsing in __call__</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c748add50d9c67f616ba98ad3a248bcc1bf0331a"><code>c748add</code></a></td><td><code>Adding kissat to SAT list of options</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3d71886a13e4bed28bd950ec8ec99688af4c4752"><code>3d71886</code></a></td><td><code>Using -model for Glucose command so that the format of the output have same format (starting with letter v)</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/18364bfbb796d990a8d853c9581c6541cf900ff9"><code>18364bf</code></a></td><td><code>making the `__call__` work whatever the DIMACS SAT solver</code></td></tr></table>

**Comment by seblabbe** [comment]
Branch: **[u/slabbe/34911](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34911)**

**Comment by seblabbe** [comment]
Commit: **[`18364bf`](https://github.com/sagemath/sagetrac-mirror/commit/18364bfbb796d990a8d853c9581c6541cf900ff9)**

**Comment by seblabbe** [comment]
Dependencies: **#34909**

**Comment by seblabbe** [comment]
Author: **Sébastien Labbé**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/961719cb929052ae09dd61142b827a6a79e397cf"><code>961719c</code></a></td><td><code>making doctests solution indenpendent</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`18364bf`](https://github.com/sagemath/sagetrac-mirror/commit/18364bfbb796d990a8d853c9581c6541cf900ff9)** to **[`961719c`](https://github.com/sagemath/sagetrac-mirror/commit/961719cb929052ae09dd61142b827a6a79e397cf)**

**Comment by seblabbe** [comment]
<div id="comment:5" align="right">comment:5</div>

My `sage -t` command is currently broken, so maybe not all tests pass. This is why I wait before setting the status to needs review.

**Comment by sheerluck** [comment]
<div id="comment:6" align="right">comment:6</div>

1) `sat/solvers/dimacs.py  # Tab character found`

2)

```
File "sage/sat/solvers/dimacs.py", lines 535, 572, 640, 707 
Expected: DIMACS Solver: 'rsat {input} {output} -v -s' 
Got:      DIMACS Solver: 'rsat {input} -v -s' 
Expected: DIMACS Solver: 'glucose -verb=2 {input} {output}'
Got:      DIMACS Solver: 'glucose -verb=0 -model {input}'
Expected: DIMACS Solver: 'glucose-syrup -model -verb=2 {input}'
Got:      DIMACS Solver: 'glucose-syrup -model -verb=0 {input}'
Expected: DIMACS Solver: 'kissat {input} {output}'
Got:      DIMACS Solver: 'kissat -q {input}'

File "sage/sat/solvers/satsolver.pyx", line 364, 369, 374 
Expected: DIMACS Solver: 'glucose -verb=2 {input} {output}'
Got:      DIMACS Solver: 'glucose -verb=0 -model {input}'
Expected: DIMACS Solver: 'glucose-syrup -model -verb=2 {input}'
Got:      DIMACS Solver: 'glucose-syrup -model -verb=0 {input}'
Expected: DIMACS Solver: 'kissat -q {input} {output}'
Got:      DIMACS Solver: 'kissat -q {input}'
```

3) without `--optional=glucose,kissat`

```
[148 tests, 0.19 s]
```

4) with `--optional=glucose,kissat`

```
[172 tests, 1.71 s]
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`961719c`](https://github.com/sagemath/sagetrac-mirror/commit/961719cb929052ae09dd61142b827a6a79e397cf)** to **[`27a3125`](https://github.com/sagemath/sagetrac-mirror/commit/27a312593d6c1a341b9b8f88dc2dce1a680d03fd)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c02693d57f380d649cda15d46a9d53c566523025"><code>c02693d</code></a></td><td><code>34909: removed line 'mkdir build' in spkg-install</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0d2f088197d90d894fffaf959a0afb1abaa3a739"><code>0d2f088</code></a></td><td><code>renaming DIMACS.__call__ as DIMACS._run; moving RSat.__call__ up to parent DIMACS.__call__; improved doc</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/93b12a644d1ed4ccc3183e01ee74f65bf0f065be"><code>93b12a6</code></a></td><td><code>Adding class Kissat</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ba249f607137ee3269f3c862381df2e1e3803a54"><code>ba249f6</code></a></td><td><code>Improved the output parsing in __call__</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b1e287d24e8c4e2584616bd8862cb438dee6dbbe"><code>b1e287d</code></a></td><td><code>Adding kissat to SAT list of options</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f97daccfb53d09f94fc7d1dc56ea470d37294fe8"><code>f97dacc</code></a></td><td><code>Using -model for Glucose command so that the format of the output have same format (starting with letter v)</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c21a080398e518447625025f597022daeed30504"><code>c21a080</code></a></td><td><code>making the `__call__` work whatever the DIMACS SAT solver</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6e7dfb7a5ab17b18fc8d2d2da81f692262f84234"><code>6e7dfb7</code></a></td><td><code>making doctests solution indenpendent</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b55a0b9f1fa5b6a43daba30dab46e5f1c24e01a4"><code>b55a0b9</code></a></td><td><code>34911: removed tabulation, fixed doctests</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/27a312593d6c1a341b9b8f88dc2dce1a680d03fd"><code>27a3125</code></a></td><td><code>34911: fixing doc build</code></td></tr></table>

**Comment by seblabbe** [comment]
<div id="comment:8" align="right">comment:8</div>

Thanks for the list. Meanwhile I fixed my `sage -t` after doing `make distclean`.

Rebased on top of the additional commit which was made in #34909.

Fixed tabulation, doctests and docbuild. Needs review!

**Comment by seblabbe** [comment]
<div id="comment:9" align="right">comment:9</div>

With `sage -pip install slabbe` done, I can now expand [the comparison of solvers](http://www.slabbe.org/blogue/2018/12/comparison-of-wang-tiling-solvers/) solving the tiling of a n times n square by Wang tiles:

```
sage: from slabbe import WangTileSet
sage: tiles = [(2,4,2,1), (2,2,2,0), (1,1,3,1), (1,2,3,2), (3,1,3,3),
....: (0,1,3,1), (0,0,0,1), (3,1,0,2), (0,2,1,2), (1,2,1,4), (3,3,1,2)]
sage: T0 = WangTileSet([tuple(str(a) for a in t) for t in tiles])
```

With glucose:

```
sage: %time T0.solver(55,55).solve(solver='glucose')
CPU times: user 1.53 s, sys: 12 ms, total: 1.54 s
Wall time: 7.07 s
A wang tiling of a 55 x 55 rectangle
sage: %time T0.solver(60,60).solve(solver='glucose')
CPU times: user 1.79 s, sys: 23.9 ms, total: 1.82 s
Wall time: 13.3 s
A wang tiling of a 60 x 60 rectangle
```

With kissat:

```
sage: %time T0.solver(55,55).solve(solver='kissat')
CPU times: user 1.53 s, sys: 19.7 ms, total: 1.55 s
Wall time: 8.84 s
A wang tiling of a 55 x 55 rectangle
sage: %time T0.solver(60,60).solve(solver='kissat')
CPU times: user 1.84 s, sys: 27.9 ms, total: 1.87 s
Wall time: 14.8 s
A wang tiling of a 60 x 60 rectangle
```

It turns out kissat is comparable but not better than glucose for this question.

Anyway, this is just to confirm the code here works.

**Comment by seblabbe** [comment]
<div id="comment:12" align="right">comment:12</div>

Thanks for the review!

Please add your complete name to the Reviewer field, as otherwise the release manager will change the status to "needs work".

**Comment by sheerluck** [comment]
Reviewer: **Andrey Belgorodski**

**Comment by vbraun** [comment]
Changed branch from **[u/slabbe/34911](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34911)** to **[`27a3125`](https://github.com/sagemath/sagetrac-mirror/commit/27a312593d6c1a341b9b8f88dc2dce1a680d03fd)**
