### ISSUE TITLE
Compute the characteristic polynomial of the Frobenius endomorphism of a Drinfeld module

### ISSUE THREAD

**Issue by ymusleh** [sagemath/sage#35028]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Problem Description

The Frobenius is a distinguished element of the endomorphism ring of a Drinfeld module, and its characteristic polynomial is considered an important invariant attached to it. There is currently a pull request [#35026](https://github.com/sagemath/sage/pull/35026) open for the implementation of Drinfeld modules; however the implementation currently only allows for the computation of the characteristic polynomial for Drinfeld modules of rank 2. 

I propose extending this implementation to allow for computing the characteristic polynomial of the Frobenius endomorphism on Drinfeld modules of any rank.

### Proposed Solution

There are algorithms that allow one to compute the characteristic polynomial in any rank. I propose implementing one of these algorithms as part of the DrinfeldModule class or a related class. A related solution could be to allow the computation of characteristic polynomials of any morphism acting on a Drinfeld module.

### Alternatives Considered

There are not really any alternatives other than the ones mentioned in proposed solution.

**Comment by kryzar** [comment]
Amazing, thank you @ymusleh!

As discussed at SageDays 117, I suggest creating multiples (private) methods to compute the characteristic polynomial of the Frobenius endomorphism, one for each algorithm. The user chooses which algorithm with the flag `algorithm` of method `frobenius_charpoly`. Example:

```
sage: chi = phi.frobenius_charpoly(algorithm='crystalline')
```

I think each method should be named `_frobenius_charpoly_algorithm` (e.g. `_frobenius_charpoly_crystalline`). We can figure out a smart way to code this.

In the long term, this code might be moved to `DrinfeldModuleMorphism` (this would not mean a deprecation because we would keep `DrinfeldModule` method `frobenius_charpoly`).
