### ISSUE TITLE
Edit button ("fork me on GitHub") for Sage documentation

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#35223]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Problem Description

Too few people work on the documentation.

### Proposed Solution

Invite viewers of our documentation to send PRs by including an edit button ("fork me on GitHub") in our HTML documentation.

https://pradyunsg.me/furo/customisation/edit-button/#with-popular-vcs-hosts

### Alternatives Considered

N/A

**Comment by kwankyu** [comment]
As far as I understand, this is not feasible for our reference manual since the reference manual is generated by autodoc and multi-doc from our source code files, which are distinct from the rst files, from which Sphinx generates the HTML documentation. The edit buttion would direct to the rst files, which are absent in our repo.

**Comment by mkoeppe** [comment]
I think what I was hoping for was implemented in:
- #25914

**Comment by kwankyu** [comment]
By the way, I am proud that the old trac ticket was converted perfectly to github :-)

**Comment by mkoeppe** [comment]
Indeed! We can enjoy this heroic achievement every time we revisit the converted tickets.

**Comment by mkoeppe** [comment]
The "Source" links on https://docs.sympy.org/latest/modules/tensor/array.html#classes also lead to the definitions of the functions in the sympy repo.

**Comment by kwankyu** [comment]
Looking back, #37589 implemented it in the sympy way.
