### ISSUE TITLE
Radicals not simplifying

### ISSUE THREAD

**Issue by grhkm21** [sagemath/sage#36309]
### Steps To Reproduce

Run `(sqrt(22)*sqrt(11)*sqrt(2)).full_simplify().expand()`

### Expected Behavior

It should simplify to `22`.

### Actual Behavior

It doesn't, it just stays unchanged.

### Additional Information

I am not sure if this is a bug or intended, since this might be related to factoring? But also it shouldn't be, since you can simplify `sqrt(p * q) * sqrt(p * r) -> p * sqrt(q * r)` by using GCD instead of factoring.

### Environment

```markdown
Sage Version: 10.1beta8
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by grhkm21** [comment]
I should have looked closer, but I just found the `.canonicalize_radical` method which successfully simplify it to `22`. Should it be included in `.full_simplify()` as well?

**Comment by orlitzky** [comment]
> It should simplify to 22.

Wherefore art thou `-22`?

If you're looking to solve `x == sqrt(22^2)` and if you make that simplification on the right hand side,  one of your solutions will disappear.

> Should it be included in `.full_simplify()` as well?

It used to be, but it caused lots of surprising bugs. The docstring for `canonicalize_radical()` gives a few more examples. It was removed because we felt that the word "simplify" strongly suggested that it wouldn't change the answer.

**Comment by grhkm21** [comment]
I see, you are right, thank you!
