### ISSUE TITLE
On the power residue symbol<title>

### ISSUE THREAD

**Issue by ys1123** [sagemath/sage#36734]
### Steps To Reproduce

As in [this asksage forum](https://ask.sagemath.org/question/74180/on-power-residue-symbol/) , `residue_symbol` command seems to have bugs.

I ran the following code:

```
def new_residue_symbol(a,P,N):
    if a not in P:
        return K(a).residue_symbol(P,N)
    else:
        return 0
N=3
K.<z>=CyclotomicField(N)
p=5
P =(K.ideal(p).factor())[0][0]#P is prime ideal above p
sum(new_residue_symbol(a,P,N) for a in P.residue_field())
``` 

### Expected Behavior

The value must be $0$ since this is the sum of  characters of a group.

### Actual Behavior

The output is `typeerror: unable to convert 0 to Cyclotomic Field of order 3 and degree 2`

### Additional Information

I am very beginner about SageMath and Python, I also asked another expert, but he also said this seems to be a bug. And he went on to say "In fact, a similar phenomenon is known to occur (to a certain extent) and has been confirmed in previous elliptic curve calculations." .

### Environment

```markdown
- **OS**:iPadOS 17.0.3
- **Sage Version**:Sage cell server
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by DaveWitteMorris** [comment]
This is user error, not a bug in sage, so I think the ticket can be closed.

1. `a` is an element of `P.residue_field()`, so it is not an element of `K`. Therefore, the test `a not in P` will always return `True`. This should be changed to `not a.is_zero()`.

2. The error comes from the expression `K(a)` and is not caused by `residue_symbol`. The element `a` is in `P.residue_field()`. To get an element of `K` from this, you need to apply a lifting map. So `K(a)` should be changed to `a.parent().lift_map()(a)`. (Or maybe there is a simpler way to write this, but `K(a)` does not work.)

Making these changes results in the correct output:
```
sage: def new_residue_symbol(a,P,N):
....:     if not a.is_zero():
....:         return a.parent().lift_map()(a).residue_symbol(P,N)
....:     else:
....:         return 0
....: 
sage: N=3
sage: K.<z>=CyclotomicField(N)
sage: p=5
sage: P =(K.ideal(p).factor())[0][0]#P is prime ideal above p
sage: sum(new_residue_symbol(a,P,N) for a in P.residue_field())
0
```

**Comment by ys1123** [comment]
Thank you! That’s certainly works. 

This is simply a question, this originally comes from [problem on jacobi sum](https://math.stackexchange.com/questions/4800822/jacobi-sum-of-power-residue-symbol-in-sagemath?noredirect=1#comment10211238_4800822). Do you know how to solve this original problem?

**Comment by DaveWitteMorris** [comment]
Sorry, you'll have to ask on the other forum. This is for issues about sage development, not for questions about how to use sage.

**Comment by ys1123** [comment]
OK, I got that :)
