### ISSUE TITLE
number_field_elements_from_algebraics incorrectly simplify root of unity?

### ISSUE THREAD

**Issue by user202729** [sagemath/sage#36735]
### Steps To Reproduce

Run
```
L, [ww], phi = number_field_elements_from_algebraics([(-1)^(2/3)])
assert ww != 1
```

### Expected Behavior

That ww become a primitive 3rd root of unity.

### Actual Behavior

ww = 1.

### Environment

```markdown
- **OS**: Linux
- **Sage Version**: SageMath version 10.1, Release Date: 2023-08-20
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by fchapoton** [comment]
Looks like a bug indeed. You could avoid using the symbolic ring:
```
sage: L, [ww], phi = number_field_elements_from_algebraics([E(3)**2])
sage: L, ww, phi
(Cyclotomic Field of order 3 and degree 2,
 -zeta3 - 1,
 Ring morphism:
   From: Cyclotomic Field of order 3 and degree 2
   To:   Algebraic Field
   Defn: zeta3 |--> -0.500000000000000? + 0.866025403784439?*I)
```

**Comment by DaveWitteMorris** [comment]
I think these are the source of the erroneous answer:
```
sage: AA((-1)^(2/3))
1
sage: from sage.symbolic.expression_conversions import algebraic
sage: algebraic((-1)^(2/3), AA)
1
```
Shouldn't they give an error, instead of converting?

**Comment by DaveWitteMorris** [comment]
Sorry, I removed the `bug` tag from the wrong ticket.

**Comment by DaveWitteMorris** [comment]
I think this is the problem:

In lines 105-110 of the method `arithmetic` of `class AlgebraicConverter(Converter)` (in src/sage/symbolic/expression_conversion/algebraic.py), we see that the expression `AA((-1)^(2/3))` is calculated as `(AA(-1))**(2/3)`. But this is not what we want, because the documentation of `AA` says "`AlgebraicReal` [is] closed under ... rational powers (including roots), except that for a negative `AlgebraicReal`, taking a power with an even denominator returns an `AlgebraicNumber` instead of an `AlgebraicReal`." This means that raising an element of `AA` to the `2/3` power will give a result that is in `AA`. That's not the answer that we want for this expression.

**Comment by mezzarobba** [comment]
See also #12074, #12745,  #18333.

**Comment by kwankyu** [comment]
> Looks like a bug indeed. You could avoid using the symbolic ring:
> 
> ```
> sage: L, [ww], phi = number_field_elements_from_algebraics([E(3)**2])
> sage: L, ww, phi
> (Cyclotomic Field of order 3 and degree 2,
>  -zeta3 - 1,
>  Ring morphism:
>    From: Cyclotomic Field of order 3 and degree 2
>    To:   Algebraic Field
>    Defn: zeta3 |--> -0.500000000000000? + 0.866025403784439?*I)
> ```

Interestingly
```sage
sage: QQbar((-1)^(1/3))
0.500000000000000? + 0.866025403784439?*I
sage: QQbar(E(3))
-0.500000000000000? + 0.866025403784439?*I
sage: QQbar((-1)^(2/3))
-0.500000000000000? + 0.866025403784439?*I
sage: QQbar(E(3)**2)
-0.500000000000000? - 0.866025403784439?*I
```
I wonder if `E` has some rules in choosing a primitive n-th root of unity, or it is just arbitrary...

Note also:
```sage
sage: L, [ww], phi = number_field_elements_from_algebraics([QQbar((-1)^(2/3))])
sage: L
Cyclotomic Field of order 6 and degree 2
sage: ww
zeta6 - 1
sage: phi
Ring morphism:
  From: Cyclotomic Field of order 6 and degree 2
  To:   Algebraic Field
  Defn: zeta6 |--> 0.500000000000000? + 0.866025403784439?*I
```
