### ISSUE TITLE
`augment()` produces a TypeError for matrices over a finite field

### ISSUE THREAD

**Issue by maxale** [sagemath/sage#36761]
### Steps To Reproduce

The following code works fine:
```
A = matrix(QQ, 3, range(12))
B = vector(QQ, range(3))
A.augment(B)
```
However, changing `QQ` to a finite field breaks it:
```
K = GF(2^2)
A = matrix(K, 3, range(12))
B = vector(K, range(3))
A.augment(B)
```

### Expected Behavior

`.augment()` should work equally well over any ring.

### Actual Behavior

The following error is produced:

> TypeError: Argument 'right' has incorrect type (expected sage.matrix.matrix_gf2e_dense.Matrix_gf2e_dense, got sage.modules.free_module_element.FreeModuleElement_generic_dense)

### Environment

```markdown
- **OS**: Ubuntu 22.04.3 LTS
- **Sage Version**: 10.2.beta5
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by DaveWitteMorris** [comment]
The title is misleading, because the problem arises when trying to augment by a vector, not by a matrix.
```
sage: K = GF(2^2)
sage: A = matrix(K, 3, range(12))
sage: B = matrix(K, 3, range(3))
sage: A.augment(B)
[0 1 0 1 0]
[0 1 0 1 1]
[0 1 0 1 0]
```
The documentation of the `augment` method for these matrices over a finite field specifies that the argument must be a matrix, so the failure for vectors is not a bug.  However, extending the method to allow vectors seems to be a very reasonable enhancement request.
