### ISSUE TITLE
factor ignores complex conjugate

### ISSUE THREAD

**Issue by jlportner** [sagemath/sage#36833]
### Steps To Reproduce

1. I run SageMath version 10.2, Release Date: 2023-12-03.
3. When I enter the following commands:
```
y = SR.var("y") # or y = var("y")
f = y * conjugate(y)
f.factor()
```

4. This returns y^2 which is clearly not true for y being complex.

### Expected Behavior

The expected result for this would be to just return y * conjugate(y) as by documentation when declaring y as a variable of SR it is assumed that y is in the complex plain.

### Actual Behavior

The factor function treats y as a real variable and thus returns the wrong result of y^2.

### Environment

```markdown
- **OS**: Arch Linux
- **Kernel**: Linux 6.6.4-arch1-1
- **Sage Version**: 10.2
- **Python Version**: 3.11.6
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by jlportner** [comment]
From my understanding the problem comes from the declaration of the `var` function in the SymbolicRing class.
```
def var(self, name, latex_name=None, n=None, domain=None):
```
Since no domain is assumed here in the default case this is passed on downwards and therefore complex is never assumed.
So either `domain=None` should be replaced with `domain =CC` or the documentation should be changed to reflect that by default the variables are actually not in the complex plane.

**Comment by jlportner** [comment]
I found it in the file `src/sage/symbolic/ring.pyx` in line 751. I don't know how to properly reference such locations.

**Comment by RuchitJagodara** [comment]
If we keep `domain=None` then also it is taking variable y in complex plane only and you can verify this by `y.is_real()` function it is giving answer false in my case,
`sage: y = var("y")
sage: y.is_real()
False`

So it is obvious that y is not real (i.e. Complex) and I also tried changing the code like below.

`def var(self, name, latex_name=None, n=None, domain="complex"):`

After changing that code also it is giving answer y^2 only.

So I think there might be an issue with the factor() function. Because it is giving the value of f as y*conjugate(y) only.

**Comment by RuchitJagodara** [comment]
I checked it and I found that the issue is with the default value only because whenever we were defining a variable without specifying any domain it was calling symbol() function with domain=None; Subsequently, it calls new_Expression_symbol() function with domain=None. In this code, I found that it was not giving any specific domain to the variable and so when we define a new variable using SR.var() function, it is passing the is_real() test but giving the wrong answer on factor() function, where we are assuming that the variable is in complex plane by default which is correct according to the documentation.

**Comment by RuchitJagodara** [comment]
@jlportner I have added a PR can you verify it ?

**Comment by dimpase** [comment]
How about 
```python
sage: y = SR.var("y", domain="complex")
sage: factor(y*conjugate(y))
y*conjugate(y)
```
I'm not sure whether making `domain="complex"` is what we want.
