### ISSUE TITLE
Function `make_nice_tree_decomposition` returns incorrect results for $K_{3}$ and $K_{2, 5}$

### ISSUE THREAD

**Issue by guojing0** [sagemath/sage#36843]
I am implementing homomorphism counting functionality, and noticed that currently the function `make_nice_tree_decomposition` does not work correctly for $K_{3}$ and $K_{2, 5}$:

```python
graph = graphs.CompleteBipartiteGraph(2, 5)  # replace by `graphs.CompleteGraph(3)` for the triangle
tree_decomp = graph.treewidth(certificate=True)
nice_tree_decomp = make_nice_tree_decomposition(graph, tree_decomp)
root = sorted(nice_tree_decomp)[0]
dir_labelled_TD = label_nice_tree_decomposition(nice_tree_decomp, root)
dir_labelled_TD.plot()
```

![图片](https://github.com/sagemath/sage/assets/3425792/94234b20-b727-4831-9477-37829c651547)

When it's $K_{3}$, it only returns a singleton.

**Comment by RuchitJagodara** [comment]
> dir_labelled_TD = label_nice_tree_decomposition(nice_tree_decomp, root, directed=True)

Here, you are passing three arguments in label_nice_tree_decomposition but it is giving me an error in my case, it says that 'label_nice_tree_decomposition() got an unexpected keyword argument 'directed'.' Can you mention the version which you are using currently, @guojing0 because I am not able to reproduce the same in my case.

**Comment by guojing0** [comment]
@RuchitJagodara Thank you for pointing out. I just changed the code. It should work now.
