### ISSUE TITLE
Simplicial Complex kernel

### ISSUE THREAD

**Issue by hockse** [sagemath/sage#37116]
### Steps To Reproduce

sage: s = simplicial_complexes.Sphere(1)
sage: nc = s.n_chains(1)
sage: nc.basis()
Finite family {(0, 1): (0, 1), (0, 2): (0, 2), (1, 2): (1, 2)}
sage: sc = s.chain_complex()
sage: df = sc.differential(1)
sage: df.kernel()
Free module of degree 3 and rank 1 over Integer Ring
Echelon basis matrix:
[1 1 1]
sage:

### Expected Behavior

kernel should be [1 -1 1]

### Actual Behavior

Out put is [1 1 1]

### Environment

```markdown
- **OS**: Conda 23.9.0
- **Sage Version**: 10.2
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by tscrim** [comment]
This isn't a bug. Yes, it is a bit surprising at first, but one needs to be careful about how the matrices are acting (on row vectors or column vectors). This can be seen when we break the symmetry in the number of vertices versus edges:
```
sage: S = SimplicialComplex([[0,1],[1,2],[2,3],[3,0],[1,3]])
sage: ascii_art(S.chain_complex())
            [-1 -1  0  0  0]
            [ 1  0 -1 -1  0]
            [ 0  0  1  0 -1]
            [ 0  1  0  1  1]
 0 <-- C_0 <----------------- C_1 <-- 0
sage: S.chain_complex().differential(1)
[-1 -1  0  0  0]
[ 1  0 -1 -1  0]
[ 0  0  1  0 -1]
[ 0  1  0  1  1]
sage: _.kernel()
Free module of degree 4 and rank 1 over Integer Ring
Echelon basis matrix:
[1 1 1 1]
```
It is simply that Sage's default kernel is the left kernel instead of the right kernel. Indeed, you get the correct answer if you ask for the `right_kernel()`.

(If you want to change this choice, you need to first ask on sage-devel.)
