### ISSUE TITLE
Polybori doctest failure

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#37732]
### Steps To Reproduce

This test failure is reproducible:
```
sage -t --random-seed=53322096094394940204738795464999058924 src/sage/rings/polynomial/pbori/pbori.pyx
**********************************************************************
File "src/sage/rings/polynomial/pbori/pbori.pyx", line 7644, in sage.rings.polynomial.pbori.pbori.gauss_on_polys
Failed example:
    E == A.echelon_form()
Expected:
    True
Got:
    False
```

### Expected Behavior

Test should pass

### Actual Behavior

Test fails

### Environment

```markdown
- **OS**: Ubuntu 22.04
- **Sage Version**: 10.4.beta1
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by S17A05** [comment]
The issue is that the code

` B.<a,b,c,d,e,f> = BooleanPolynomialRing()
  from sage.rings.polynomial.pbori.pbori import *
  l = [B.random_element() for _ in range(B.ngens())]
  A, v = Sequence(l, B).coefficients_monomials()`

creates a $6 \times 15$ matrix, but for the given seed two of the random elements in `l` are actually the same. This redundant element is removed by `.gauss_on_polys`, which is why the associated matrix of the resulting sequence is of size $5 \times 15$; the difference between the two matrices is then one additional row of zeroes in `A.echelon_form()`.
