### ISSUE TITLE
Docstring of __call__ does not appear in the HTML documentation?

### ISSUE THREAD

**Issue by user202729** [sagemath/sage#38480]
Example:

* the following documentation https://github.com/sagemath/sage/blob/develop/src/sage/lfunctions/dokchitser.py#L490-L507 is not included in https://doc.sagemath.org/html/en/reference/lfunctions/sage/lfunctions/dokchitser.html
* the following documentation https://github.com/sagemath/sage/blob/develop/src/sage/rings/valuation/valuation_space.py#L211-L218 is not included in https://doc.sagemath.org/html/en/reference/valuations/sage/rings/valuation/valuation_space.html

**Comment by thecaligarmo** [comment]
This is by design. No private methods (methods which start with a `_`) are listed in the documentation. As far as I'm aware there is no movement to alter this behavior globally. Maybe @mkoeppe might have more details on this.

There are two alternatives:
1. If you have a local version of sage, you can have the documentation show all methods (even private ones) by setting `SAGE_DOC_UNDERSCORE` as an environmental variable. You would then need to `make` sage again to get the updated documentation (make sure `SAGE_DOC_UNDERSCORE` appears as an environmental variable).
2. You can add `.. automethod:: __call__` for each class you'd like the `__call__` method to appear in the documentation. (If you have a list and would prefer someone else handle it, just add the list as a comment and I can take care of it)
