### ISSUE TITLE
Implement subs or __call__ for FunctionFieldElement

### ISSUE THREAD

**Issue by vincentmacri** [sagemath/sage#38514]
### Problem Description

`FunctionFieldElement` inherits from `Element` and so it should have a working `subs` function if the notion of substitution makes sense (which I think it does in this case).

### Proposed Solution

This can be added by implementing `__call__` for `FunctionFieldElement` as the `subs` implemented in `Element` will fall back to `__call__`. This solution also allows for easier function calling syntax.

### Alternatives Considered

Implementing `subs` instead of `__call__` would work but wouldn't allow the easier function calling syntax.

### Additional Information

Example:
```python
K = GF(7)
Kx.<x> = FunctionField(K)
y = polygen(Kx)
f = x^6 + 3

# I think these should return 2^6 + 3 = 67 = 4 (mod 7)
f(2) # TypeError
f.subs(x=2) # x^6 + 3
```

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by DaveWitteMorris** [comment]
Thanks for the report. It seems to me that the current behaviour of `subs` is unacceptable and qualifies as a bug. (The documentation says it "Substitutes given generators with given values ...", but the method is not doing that.)

On the other hand, it was decided not to allow function-call syntax in situations like this. The problem is that users often forget to type the symbol `*` for multiplication.  For example, they might type `x(x + 1)` when they meant `x*(x + 1)`. When function-call syntax was allowed, sage returned `x + 1` for `x(x + 1)`, which was very bad.

**Comment by vincentmacri** [comment]
> On the other hand, it was decided not to allow function-call syntax in situations like this. The problem is that users often forget to type the symbol `*` for multiplication. For example, they might type `x(x + 1)` when they meant `x*(x + 1)`. When function-call syntax was allowed, sage returned `x + 1` for `x(x + 1)`, which was very bad.

So implementing just `subs` and not `__call__` would be the way to go then? I'll probably try to submit a PR in the next couple weeks to fix this bug.

**Comment by DaveWitteMorris** [comment]
Yes, that would be great.
