### ISSUE TITLE
external Pari 2.17 does not work (yet) 

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#38769]
### Steps To Reproduce

If Pari 2.17 is installed system-wide, it could be picked up, but doesn't work.

### Expected Behavior

Sage should not use Pari 2.17

### Actual Behavior

it does

### Additional Information

it's a 1-line fix in pari's spkg-configure.m4
Ban versions $\geq 135424$

### Environment

- **OS**: macOS 15.0.1 + Homebrew
- **Sage Version**: all

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by jhpalmieri** [comment]
Related: #38749 (upgrade pari to 2.17).

**Comment by antonio-rojas** [comment]
> Related: #38749 (upgrade pari to 2.17). It's not clear to me how close that is to being ready, though.

The sagelib part is mostly ready (I just need to push some fixes for test failures caused by different ideal and unit group generators). However, that's just a small part of the story: most of the breakage is in cypari, which would need a new release including https://github.com/sagemath/cypari2/pull/165 and https://github.com/sagemath/cypari2/pull/166. And, to make things worse, 2.17.0 ships with a bug that breaks cypari build. So 2.17.0 should probably be unconditionally disallowed, and once 2.17.1 is released we should upgrade pari and cypari in sage.

**Comment by jhpalmieri** [comment]
> it's a 1-line fix in pari's spkg-configure.m4 Ban versions ≥ 135424

Not surprisingly, this works well, fixes the problem for me. I've opened a PR that makes this change.
