### ISSUE TITLE
numerical_integral with parameters always returns 0

### ISSUE THREAD

**Issue by neldredge-unco** [sagemath/sage#39088]
### Steps To Reproduce

Following the manual entry for `numerical_integral`, I tried
```
var('x a')
f(x,a)=a*x
numerical_integral(f(x,a),0,1, params=[1])
```

[Try on SageMathCell](https://sagecell.sagemath.org/?z=eJwrSyzSUK9QSFTX5OVK06jQSdS0TdSq4OXKK81NLcpMTsyJz8wrSU0vSszRgEjrGOgY6igUJBYl5hbbRhvGagIAmmoUPQ==&lang=sage&interacts=eJyLjgUAARUAuQ==)

### Expected Behavior

Expected the value 0.5, which is the integral of `a*x` from 0 to 1 when `a = 1`.

### Actual Behavior

Output is a large blank space followed by `(0.0, 0.0)`.

### Environment

- **OS**: MacOS 15.1.1
- **Sage Version**: 10.4

Also reproducible on SageMathCell (see permalink above).

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by DaveWitteMorris** [comment]
Thanks for the bug report.  

Processing of the `params` argument seems to have been broken for quite a while. (I tested Sagemath 9.6, which is the oldest available on CoCalc.) Unfortunately, the doctest is marked "`# random output (architecture and os dependent)`", so it does not actually get tested. After we fix the problem, I think the doctest should be given an appropriate error bound, instead of being marked "`# random`" (or another doctest should be added that will not be ignored).
